# The URL the site will be built for
base_url = "https://jwm-dev.github.io"
title = "║ 𝕛𝕨𝕞-𝕕𝕖𝕧 ║"
theme = "ergo"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
#highlight_theme = "solarized-light"

[extra]
# Put all your custom variables here

profile = "portrait.png"
description = "Portfolio and networking site for Jeffrey Gregory, AKA jwm-dev."
color_themes = ["dark", "default"]

[extra.font_awesome]
kit = "d203275317"

[[extra.socials]]
icon = "github"
display = "jwm-dev @ github"
uri = "https://github.com/jwm-dev"

[[extra.socials]]
icon = "linkedin"
display = "Jeffrey G. @ Linked"
uri = "https://www.linkedin.com/in/jeffrey-gregory-b26853294/"

[[extra.socials]]
icon = "envelope"
icon_class = "fas"
display = "Mail"
uri = "mailto:$jwmgregory@gmail.com?subject=[Hello, jwm!]"

[[extra.socials]]
icon = "phone"
icon_class = "fas"
display = "Cellular"
uri = "tel:+14057785170"
