# The URL the site will be built for
base_url = "https://jwm-dev.github.io"
title = "║ 𝕛𝕨𝕞-𝕕𝕖𝕧 ║"
theme = "ergo"

description="\"*... If the meaning of the words \\\"machine\\\" and \\\"think\\\" are to be found by examining how they are commonly used, it is difficult to escape the conclusion that the meaning and the answer to the question, 'Can machines think?' is to be sought in a statistical survey such as a Gallup poll. But this is absurd.*\" \n\n- Alan M. Turing, *\"Computing Machinery and Intelligence,\"*  \n01 October 1950"
default_language = "en"

generate_feeds = true
feed_filenames = ["atom.xml"]
feed_limit = 20

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
#highlight_theme = "solarized-light"

[extra]
# Put all your custom variables here

profile = "portrait.png"
country_flags = true
color_themes = ["dark", "default"]

[extra.font_awesome]
kit = "d203275317"

[[extra.socials]]
icon = "github"
display = "jwm-dev@gh"
uri = "https://github.com/jwm-dev"

[[extra.socials]]
icon = "linkedin"
display = "Jeffrey@Linked"
uri = "https://www.linkedin.com/in/jeffrey-gregory-b26853294/"

[[extra.socials]]
icon = "envelope"
icon_class = "fas"
display = "Mail"
uri = "mailto:$jwmgregory@gmail.com?subject=[Hello, jwm!]"

[[extra.socials]]
icon = "phone"
icon_class = "fas"
display = "Cellular"
uri = "tel:+14057785170"
